name: SPC OH Post 0900

on:
  workflow_dispatch:
    inputs:
      force:
        description: "Force update"
        required: false
        default: "false"

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Post All Days
        run: |
         curl -H "Content-Type: application/json" \
          -d "{
            \"content\":\"🔔 9:00AM Update!\\n\\n 🔁 Next Update: 12:30PM\"
          }" \
          ${{ secrets.DISCORD_WEBHOOK }}

          sleep 2

          TIMESTAMP=$(date +%s)
          curl -H "Content-Type: application/json" \
          -d "{
            \"embeds\":[
              {
                \"title\":\"🌪️ OH Day 1 Tornado Outlook\",
                \"image\":{\"url\":\"https://www.spc.noaa.gov/partners/outlooks/state/images/OH_swody1_TORN.png?t=$TIMESTAMP\"}
              },
              {
                \"title\":\"🌪️ OH Day 2 Tornado Outlook\",
                \"image\":{\"url\":\"https://www.spc.noaa.gov/partners/outlooks/state/images/OH_swody2_TORN.png?t=$TIMESTAMP\"}
              }
            ]
          }" \
          ${{ secrets.DISCORD_WEBHOOK }}

          sleep 5

          TIMESTAMP=$(date +%s)
          curl -H "Content-Type: application/json" \
          -d "{
            \"embeds\":[
              {
                \"title\":\"⛈️ OH Day 1 Severe Outlook\",
                \"image\":{\"url\":\"https://www.spc.noaa.gov/partners/outlooks/state/images/OH_swody1.png?t=$TIMESTAMP\"}
              },
              {
                \"title\":\"⛈️ OH Day 2 Severe Outlook\",
                \"image\":{\"url\":\"https://www.spc.noaa.gov/partners/outlooks/state/images/OH_swody2.png?t=$TIMESTAMP\"}
              },
              {
                \"title\":\"⛈️ OH Day 3 Severe Outlook\",
                \"image\":{\"url\":\"https://www.spc.noaa.gov/partners/outlooks/state/images/OH_swody3_PROB.png?t=$TIMESTAMP\"}
              },
              {
                \"title\":\"⛈️ OH Day 4 Severe Outlook\",
                \"image\":{\"url\":\"https://www.spc.noaa.gov/partners/outlooks/state/images/OH_swody4_PROB.png?t=$TIMESTAMP\"}
              },
              {
                \"title\":\"⛈️ OH Day 5 Severe Outlook\",
                \"image\":{\"url\":\"https://www.spc.noaa.gov/partners/outlooks/state/images/OH_swody5_PROB.png?t=$TIMESTAMP\"}
              }
            ]
          }" \
          ${{ secrets.DISCORD_WEBHOOK }}
