name: SPC OH Post TEST

on:
  workflow_dispatch:
    inputs:
      force:
        description: "Force update"
        required: false
        default: "false"

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Post All Days
        run: |
          TIMESTAMP=$(date +%s)

          curl -H "Content-Type: application/json" \
          -d "{
            \"content\":\"🌩️ [Day 4](<https://www.spc.noaa.gov/partners/outlooks/state/images/OH_swody3_PROB.png?t=$TIMESTAMP>) 🌩️ [Day 5](<https://www.spc.noaa.gov/partners/outlooks/state/images/OH_swody5_PROB.png?t=$TIMESTAMP>)\"
          }" \
          ${{ secrets.DISCORD_WEBHOOK }}
            
